### PR TITLE
libusbgx: fix build with glibc-2.28 since <sys/sysmacros.h> is no more included by <sys/types.h>

### PR DESCRIPTION
**Pull request by trabucayre**
Since https://sourceware.org/ml/libc-alpha/2015-11/msg00253.html sys/sysmacros.h must be explicitly included.
Without sys/sysmacros.h and with glibc-2.28 build fails with error like:
src/.libs/libusbgx.so: undefined reference to `minor'
src/.libs/libusbgx.so: undefined reference to `major'
src/.libs/libusbgx.so: undefined reference to `makedev'

pull request based on https://github.com/libusbgx/libusbgx/pull/28

Signed-off-by: Sid Spry <R030t1@gmail.com>
Signed-off-by: Gwenhael Goavec-Merou <gwenhael.goavec-merou@trabucayre.com>

### CODE REVIEW

**Comment by kopasiak** [comment]
Merged. Thank you for your contribution.
